spring:
  datasource:
    url: jdbc:h2:mem:database
    username: user
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    cleanDisabled: false
    cleanOnValidationError: true
