create sequence seq_contact_id minvalue 1 maxvalue 99999999 increment by 1 no cycle;

create table contact
(
    id                  int8 generated by default as identity,
    key_id              varchar(64) not null,
    created_date        timestamp,
    last_modified_date  timestamp,
    first_name          varchar not null,
    last_name           varchar not null,
    email               varchar not null,
    phone_number        varchar,
    address_street      varchar,
    address_post_code   varchar,
    address_city        varchar,
    primary key (id)
);

create index idx_contact_id on contact (id);

create index idx_contact_key_id on contact (key_id);

alter table contact
add constraint uq_contact_key_id unique (key_id);

alter table contact
add constraint uq_contact_email unique (email);