create sequence seq_skill_id minvalue 1 maxvalue 99999999 increment by 1 no cycle;

create table skill (
    id                  int8 generated by default as identity,
    key_id              varchar(64) not null,
    created_date        timestamp,
    last_modified_date  timestamp,
    name                varchar not null,
    level               varchar not null,
    primary key (id)
);

create index idx_skill_id on skill (id);

create index idx_skill_key_id on skill (key_id);

alter table skill
add constraint uq_skill_key_id unique (key_id);

alter table skill
add constraint uq_skill_name_level unique (name, level);